# Generated by Django 3.1.7 on 2021-03-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('soil', models.FloatField()),
                ('temp', models.FloatField()),
                ('hum', models.FloatField()),
                ('msg', models.TextField()),
            ],
        ),
    ]
